# run this file with gcloud builds submit --substitutions=_TAG=v1 

steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "asia.gcr.io/$PROJECT_ID/$PROJECT_ID:$_TAG",
       "--build-arg", "project_id=$PROJECT_ID", "."]
images: ["asia.gcr.io/$PROJECT_ID/$PROJECT_ID:$_TAG"]
